#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("paujo.juze.android.Resource", IsApplication=true)]

namespace paujo.juze.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadeInAnimation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeOutAnimation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fromLeftAnimation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int toLeftAnimation = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int faFragmentView = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int fdAcceptBtn = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int fdCancelBtn = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int fdControlLayout = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int fdNameField = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int fdNameLabel = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int fdPFBtn = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int fdPGBtn = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int fdPGLabel = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int fdRecPercField = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int fdRecPercLabel = 2131165191;
			
			// aapt resource value: 0x7f070024
			public const int jlCreateElement = 2131165220;
			
			// aapt resource value: 0x7f07000d
			public const int mDumpFlavorCountBtn = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int mDumpNicotineCountBtn = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int mListFlavorsBtn = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int mNicotineBtn = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int mRecipeBtn = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int mResetDataBaseBtn = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int naFragmentView = 2131165201;
			
			// aapt resource value: 0x7f07001a
			public const int ndAcceptBtn = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int ndCancelBtn = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int ndConcField = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int ndConcLabel = 2131165208;
			
			// aapt resource value: 0x7f070012
			public const int ndLayout = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int ndNameField = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int ndNameLabel = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int ndPGLabel = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int ndPGSlider = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int ndPGValueLabel = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int raFragmentView = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int rdNameField = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int rdNicotineField = 2131165214;
			
			// aapt resource value: 0x7f070021
			public const int rdPGLabel = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int rdPGSlider = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int rdTargetNicField = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int srRemoveBtn = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int srText = 2131165218;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FlavorActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FlavorDetailLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NicotineActivityLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NicotineDetailLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NicotineRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RecipeActivityLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RecipeDetailLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SimpleRow = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int JuzeListMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int AcceptFlavor = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int CancelFlavor = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int CreateElement = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int DefaultFlavorName = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int DefaultNicotineName = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int FlavorName = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int NicConc = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int NicName = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int NicPG = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int PGBased = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int RecPercent = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int rdNicotine = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int rdPG = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int rdRecipeName = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int rdTargetNicotine = 2131034125;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
