#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("paujo.juze.android.Resource", IsApplication=true)]

namespace paujo.juze.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XamSvg.Resource.Attribute.colorMapping = global::paujo.juze.android.Resource.Attribute.colorMapping;
			global::XamSvg.Resource.Attribute.colorMappingSelected = global::paujo.juze.android.Resource.Attribute.colorMappingSelected;
			global::XamSvg.Resource.Attribute.loadAsync = global::paujo.juze.android.Resource.Attribute.loadAsync;
			global::XamSvg.Resource.Attribute.svg = global::paujo.juze.android.Resource.Attribute.svg;
			global::XamSvg.Resource.Attribute.traceEnabled = global::paujo.juze.android.Resource.Attribute.traceEnabled;
			global::XamSvg.Resource.Styleable.SvgImageView = global::paujo.juze.android.Resource.Styleable.SvgImageView;
			global::XamSvg.Resource.Styleable.SvgImageView_colorMapping = global::paujo.juze.android.Resource.Styleable.SvgImageView_colorMapping;
			global::XamSvg.Resource.Styleable.SvgImageView_colorMappingSelected = global::paujo.juze.android.Resource.Styleable.SvgImageView_colorMappingSelected;
			global::XamSvg.Resource.Styleable.SvgImageView_loadAsync = global::paujo.juze.android.Resource.Styleable.SvgImageView_loadAsync;
			global::XamSvg.Resource.Styleable.SvgImageView_svg = global::paujo.juze.android.Resource.Styleable.SvgImageView_svg;
			global::XamSvg.Resource.Styleable.SvgImageView_traceEnabled = global::paujo.juze.android.Resource.Styleable.SvgImageView_traceEnabled;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int colorMapping = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int colorMappingSelected = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int loadAsync = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int svg = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int traceEnabled = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int cfControlLayout = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int cfCreateBtn = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int cfMainLayout = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int cfNameField = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int cfNameLabel = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int cfPFBtn = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int cfPGBtn = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int cfPGLabel = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int cfRecPercField = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int cfRecPercLabel = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int mCreateFlavorBtn = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateFlavor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int CreateFlavor = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int CreateFlavorCanceled = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int EditFlavor = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int FlavorName = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int JuzeName = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int PGBased = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int RecPercent = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SvgImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int SvgImageView_colorMapping = 1;
			
			// aapt resource value: 2
			public const int SvgImageView_colorMappingSelected = 2;
			
			// aapt resource value: 4
			public const int SvgImageView_loadAsync = 4;
			
			// aapt resource value: 0
			public const int SvgImageView_svg = 0;
			
			// aapt resource value: 3
			public const int SvgImageView_traceEnabled = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
