#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("paujo.juze.android.Resource", IsApplication=true)]

namespace paujo.juze.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadeInAnimation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeOutAnimation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fromLeftAnimation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int toLeftAnimation = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int faFragmentView = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int fdAcceptBtn = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int fdCancelBtn = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int fdControlLayout = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int fdNameField = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int fdNameLabel = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int fdPFBtn = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int fdPGBtn = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int fdPGLabel = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int fdRecPercField = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int fdRecPercLabel = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int flCreateFlavor = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int lfrRemoveBtn = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int lfrText = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int mDumpFlavorCountBtn = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int mListFlavorsBtn = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int mNicotineBtn = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int naFragmentView = 2131099665;
			
			// aapt resource value: 0x7f06001a
			public const int ndAcceptBtn = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int ndCancelBtn = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int ndConcField = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int ndConcLabel = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int ndLayout = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int ndNameField = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int ndNameLabel = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int ndPGLabel = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int ndPGSlider = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int ndPGValueLabel = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FlavorActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FlavorDetailLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FlavorListMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FlavorListRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NicotineActivityLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NicotineDetailLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int AcceptFlavor = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int CancelFlavor = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int CreateFlavor = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int DefaultFlavorName = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int FlavorName = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int NicConc = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int NicName = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int NicPG = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int PGBased = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int RecPercent = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
